### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by chaithanya762** [SaiHitesh16/Glaucoma-Detection-using-CNN#4]
Can you please share google drive files & h5 model format file please

**Comment by SaiHitesh16** [comment]
what files you need?

**Comment by chaithanya762** [comment]
.h5 format file. Bro my model is suffering from over fitting & very low accuracy , validation accuracy is also not great what should I do ? Over fitting started to occur at 50 epochs itself. I'm running it on Google collab. Please guide me

**Comment by chaithanya762** [comment]
My mail id- chaithanyagowda762@gmail.com 
If u have done some modifications to improve the accuracy please let me know , also I wanted a streamlit code for ur app , to add my improvisations , can you please share it if u don't mind

**Comment by SaiHitesh16** [comment]
I have shared .h5 file link.

**Comment by chaithanya762** [comment]
Thanks a lot 😊 can you share your streamlit code too, the user interface is great. Just wanted to check out the app code

**Comment by SaiHitesh16** [comment]
> .h5 format file. Bro my model is suffering from over fitting & very low accuracy , validation accuracy is also not great what should I do ? Over fitting started to occur at 50 epochs itself. I'm running it on Google collab. Please guide me

Try changing split ratio, re-run the epochs code to check if there is any change,also try to increase the epochs value and check

**Comment by SaiHitesh16** [comment]
> Thanks a lot 😊 can you share your streamlit code too, the user interface is great. Just wanted to check out the app code

Sorry,I don't have file in hand to share
