### ISSUE TITLE
Request 1

### ISSUE THREAD

**Issue by Vishal321kumar** [SaiHitesh16/Glaucoma-Detection-using-CNN#5]
Hi Hitesh,
Hope you are doing well 
can you pls share the .h5 model of glaucoma detection using cnn project

pls make it quick as our final presentation is near
it is really needed 
i forgot to ask for it in our last conversation for this?

Thanks in advance

**Comment by SaiHitesh16** [comment]
Hello Vishal, did you run code , it generates .h5 file right?

**Comment by Vishal321kumar** [comment]
yep mine model accuracy is 69%
that's why i want yours

**Comment by SaiHitesh16** [comment]
your faculty can know, ok share your email

**Comment by Vishal321kumar** [comment]
email - ironultimate321@gmail.com

**Comment by Vishal321kumar** [comment]
they won't see it , this one is  the final presentation earlier ones went fine

**Comment by SaiHitesh16** [comment]
I have shared, download the file
